### ISSUE TITLE
build running forever when job execute script java -jar 

### ISSUE THREAD

**Issue by onlyWuj** [gitlabhq/gitlab-ci-runner#146]
my  .gitlab-ci.yml  is very quite , below as
----------------------------------------
```
stages:
  - test

job_deploy:
  stage: test
  script:
    - call mvn  clean  package -Dmaven.test.skip=true
    - java -jar ./scf-assemble/target/scf.jar
```
--------------------------------------
![qq 20170309195933](https://cloud.githubusercontent.com/assets/24384154/23749479/5661610a-0503-11e7-8c68-fa5e4116da69.jpg)

tomcat started and hang-up, but the gitlab ci didn't receive an end signal then running forerver.
--------------------------------------
my server is windows .
all I want is simply start a web application .
how to handle this in the simplest way.
